<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 *
 * @generated
 * @phutil-library-version 2
 */
phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' => array(
    'ArcanistESLintEngine' => 'lint/engine/ArcanistESLintEngine.php',
    'ArcanistESLintLinter' => 'lint/linter/ArcanistESLintLinter.php',
    'ArcanistSCSSLintLinter' => 'lint/linter/ArcanistSCSSLintLinter.php',
    'CustomKarmaTestEngine' => 'unit/engine/CustomKarmaTestEngine.php',
  ),
  'function' => array(),
  'xmap' => array(
    'ArcanistESLintEngine' => 'ArcanistLintEngine',
    'ArcanistESLintLinter' => 'ArcanistExternalLinter',
    'ArcanistSCSSLintLinter' => 'ArcanistExternalLinter',
    'CustomKarmaTestEngine' => 'ArcanistUnitTestEngine',
  ),
));
